# Generated by Django 6.1 on 2026-08-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title_en", models.CharField(max_length=200)),
                ("title_fr", models.CharField(blank=True, max_length=200)),
                ("body_en", models.TextField()),
                ("body_fr", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="StoreInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(default="Musango Cakes & More", max_length=150),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="+000000000000",
                        help_text="Placeholder until the real business WhatsApp number is supplied.",
                        max_length=30,
                    ),
                ),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("x_url", models.URLField(blank=True)),
                (
                    "address_text",
                    models.CharField(
                        blank=True, default="Douala, Cameroon", max_length=200
                    ),
                ),
                ("maps_embed_url", models.URLField(blank=True)),
                ("directions_url", models.URLField(blank=True)),
                ("opening_hours", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": "store info",
            },
        ),
    ]
